#AI model 
model: 
  - Depth-Anythin-V2.bin,https://huggingface.co/qualcomm/Depth-Anything-V2/resolve/19ce3645e11de17eed7e869eebcc07dd352834f3/Depth-Anything-V2.bin?download=true

# apt packages
apt:
  - ros-jazzy-cv-bridge
  - ros-jazzy-image-publisher
  - python3-opencv
  - python3-numpy
  - ros-jazzy-qrb-ros-camera
  - ros-jazzy-qrb-ros-nn-inference

# python packages
pip:
